
title: Jorginho's Hair Style
description: >
    Salão de Beleza da cabeça aos pés.
    
    Ser bela é um direito de toda mulher! 
    Oferecemos uma estrutura completa para vc e toda sua família. 
    Nosso Salão conta com serviços de cabeleireiro, maquiador, manicure, 
    pedicure, podologia, depilação, designer de sobrancelhas, espaço gourmet 
    e estacionamento próprio e gratuito com manobristas.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jorginhoshair.com.br" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude:
  - gulpfile.js
  - desktop.ini

sass:
  style: compressed

plugins:
  - jekyll-coffeescript

collections:
  sections:
    output: true
