
title: Jorginho's Hair Style
description: >
  O salão oferece uma infraestrutura preparada para as necessidades dos
  profissionais e o conforto das clientes. Também oferece manobrista e
  estacionamento seguro e gratuito, além de uma boutique de roupas,
  acessórios, semi jóias, perfumes, cosméticos e um aconchegante espaço gourmet.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jorginhoshair.com.br" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude:
  - gulpfile.js
  - desktop.ini

sass:
  style: compressed

gems:
  - jekyll-coffeescript